version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - ./logs:/workspace/logs
    working_dir: /workspace
    command: python -m app.main
    # command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://developer:password@db:5432/mldb
      - MINIO_ENDPOINT=minio:9000
      - CLEARML_WEB_HOST=https://app.clear.ml/
      - CLEARML_API_HOST=https://api.clear.ml
      - CLEARML_FILES_HOST=https://files.clear.ml
      - CLEARML_API_ACCESS_KEY=QC5OFNEX5P4DFHMNSCIWMT5CD1Y5GG
      - CLEARML_API_SECRET_KEY=Ihi4R6l8lxhrocwF5mt4J_8oYRJEP5pWhzFH8KQY30XoEzRe-Qf_Bre7cO3jk-quOdE
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - CLEARML_DEFAULT_OUTPUT_URI=s3://ml-models
      - S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - db
      - minio
    expose:
      - "8000"
      - "50051"
    networks:
      - webnet
      - appnet
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "50052:50052"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/grpc.conf.d:/etc/nginx/grpc.conf.d:ro
    depends_on:
      - app
    networks:
      - webnet
  db: # это на случай если будет аутентификация
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mldb
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # оставяю так как это не прод
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # оставяю так как это не прод
      - "9001:9001" # оставяю так как это не прод
    volumes:
      - minio_data:/data
    networks:
      - appnet

volumes:
  postgres_data:
  minio_data:
networks:
  webnet:
    driver: bridge
  appnet:
    driver: bridge 